In [1]:
import numpy as np
import pandas as pd

In [ ]:
digital_wallet_df=pd.read_csv("data/digital_wallet.csv")

In [3]:
digital_wallet_df.head()

,Customer_ID,Age,Location,Income_Level,Total_Transactions,Avg_Transaction_Value,Max_Transaction_Value,Min_Transaction_Value,Total_Spent,Active_Days,Last_Transaction_Days_Ago,Loyalty_Points_Earned,Referral_Count,Cashback_Received,App_Usage_Frequency,Preferred_Payment_Method,Support_Tickets_Raised,Issue_Resolution_Time,Customer_Satisfaction_Score,LTV
0,cust_0000,54,Urban,Low,192,16736.38402,60216.83451,6525.814861,3.213386e+06,140,209,2114,25,2224.012140,Monthly,Debit Card,3,61.568590,1,3.279546e+05
1,cust_0001,67,Suburban,High,979,14536.73468,48350.10027,2186.742245,1.423146e+07,229,240,2960,20,4026.823518,Monthly,UPI,17,60.392889,8,1.437053e+06
2,cust_0002,44,Urban,High,329,7061.37280,32521.15719,2743.406808,2.323192e+06,73,21,3170,0,1441.011395,Monthly,Debit Card,11,45.305579,4,2.419387e+05
3,cust_0003,30,Rural,High,71,16426.87645,17827.89672,4360.784994,1.166308e+06,299,285,4756,35,4365.855580,Weekly,Wallet Balance,6,22.030191,1,1.284599e+05
4,cust_0004,58,Urban,Middle,878,10800.09266,17497.63453,4532.872520,9.482481e+06,236,329,1992,18,4161.523827,Daily,UPI,18,20.634723,5,9.569514e+05

In [4]:
digital_wallet_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7000 entries, 0 to 6999
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Customer_ID                  7000 non-null   object
 1   Age                          7000 non-null   int64
 2   Location                     7000 non-null   object
 3   Income_Level                 7000 non-null   object
 4   Total_Transactions           7000 non-null   int64
 5   Avg_Transaction_Value        7000 non-null   float64
 6   Max_Transaction_Value        7000 non-null   float64
 7   Min_Transaction_Value        7000 non-null   float64
 8   Total_Spent                  7000 non-null   float64
 9   Active_Days                  7000 non-null   int64
 10  Last_Transaction_Days_Ago    7000 non-null   int64
 11  Loyalty_Points_Earned        7000 non-null   int64
 12  Referral_Count               7000 non-null   int64
 13  Cashback_Received            7000 non-null   float64
 14  App_Usage_Frequency          7000 non-null   object
 15  Preferred_Payment_Method     7000 non-null   object
 16  Support_Tickets_Raised       7000 non-null   int64
 17  Issue_Resolution_Time        7000 non-null   float64
 18  Customer_Satisfaction_Score  7000 non-null   int64
 19  LTV                          7000 non-null   float64
dtypes: float64(7), int64(8), object(5)
memory usage: 1.1+ MB

In [5]:
digital_wallet_df.dtypes

Customer_ID                     object
Age                              int64
Location                        object
Income_Level                    object
Total_Transactions               int64
Avg_Transaction_Value          float64
Max_Transaction_Value          float64
Min_Transaction_Value          float64
Total_Spent                    float64
Active_Days                      int64
Last_Transaction_Days_Ago        int64
Loyalty_Points_Earned            int64
Referral_Count                   int64
Cashback_Received              float64
App_Usage_Frequency             object
Preferred_Payment_Method        object
Support_Tickets_Raised           int64
Issue_Resolution_Time          float64
Customer_Satisfaction_Score      int64
LTV                            float64
dtype: object

In [6]:
digital_cont=digital_wallet_df.select_dtypes(include=["int64","float64"])

In [7]:
digital_cat=digital_wallet_df.select_dtypes(include=["object"])

In [8]:
digital_wallet_df.isna().sum()

Customer_ID                    0
Age                            0
Location                       0
Income_Level                   0
Total_Transactions             0
Avg_Transaction_Value          0
Max_Transaction_Value          0
Min_Transaction_Value          0
Total_Spent                    0
Active_Days                    0
Last_Transaction_Days_Ago      0
Loyalty_Points_Earned          0
Referral_Count                 0
Cashback_Received              0
App_Usage_Frequency            0
Preferred_Payment_Method       0
Support_Tickets_Raised         0
Issue_Resolution_Time          0
Customer_Satisfaction_Score    0
LTV                            0
dtype: int64

#customer

In [9]:
#Avg_transactions by customer
Avg_transactions=digital_wallet_df["Total_Transactions"].mean()
int(Avg_transactions)

501

In [10]:
#Avg_transaction value by customer
Avg_transaction_value=digital_wallet_df["Avg_Transaction_Value"].mean()
Avg_transaction_value

np.float64(9946.831481979612)

In [11]:
#Avg max transaction value by customer
Avg_max_transaction_value=digital_wallet_df["Max_Transaction_Value"].mean()
Avg_max_transaction_value

np.float64(30159.596784442245)

In [12]:
#Avg min transaction value by customer
Avg_min_transaction_value=digital_wallet_df["Min_Transaction_Value"].mean()
Avg_min_transaction_value

np.float64(2981.5499528231917)

In [13]:
#Avg spent by customer
Avg_total_spent=digital_wallet_df["Total_Spent"].mean()
Avg_total_spent

np.float64(5002021.885018049)

In [14]:
#Avg actiove days by customer
Avg_Active_Days=digital_wallet_df["Active_Days"].mean()
int(Avg_Active_Days)

181

In [15]:
#Avg Loyalty_Points_Earned by customer
Avg_Loyalty_Points_Earned=digital_wallet_df["Loyalty_Points_Earned"].mean()
int(Avg_Loyalty_Points_Earned)

2501

In [16]:
#Avg Referral_Count by customer
Avg_Referral_Count=digital_wallet_df["Referral_Count"].mean()
int(Avg_Referral_Count)

24

In [17]:
#Avg Cashback_Received by customer
Avg_Cashback_Received=digital_wallet_df["Cashback_Received"].mean()
Avg_Cashback_Received

np.float64(2496.5250323687515)

In [18]:
#Avg Support_Tickets_Raised by customer
Avg_Support_Tickets_Raised=digital_wallet_df["Support_Tickets_Raised"].mean()
int(Avg_Support_Tickets_Raised)

10

In [19]:
#Avg Issue_Resolution_Time by customer
Avg_Issue_Resolution_Time=digital_wallet_df["Issue_Resolution_Time"].mean()
Avg_Issue_Resolution_Time

np.float64(36.528006773780284)

In [20]:
#Avg Customer_Satisfaction_Score by customer
Avg_Customer_Satisfaction_Score=digital_wallet_df["Customer_Satisfaction_Score"].mean()
int(Avg_Customer_Satisfaction_Score)

5

In [21]:
#Avg LTV by customer
Avg_LTV=digital_wallet_df["LTV"].mean()
Avg_LTV

np.float64(511919.7168390623)

In [22]:
# list(map(lambda x : digital_wallet_df[x].value_counts(),digital_wallet_df))

#Age

In [23]:
#Age wise average transactions
Avg_transactions_by_age=digital_wallet_df.groupby(by=["Age"]).agg({"Total_Transactions":"mean"}).reset_index()
Avg_transactions_by_age=Avg_transactions_by_age.sort_values(by=["Total_Transactions"],ascending=[False]).reset_index(drop=True)
Avg_transactions_by_age["Total_Transactions"]=Avg_transactions_by_age["Total_Transactions"].astype('int')

In [24]:
#Age wise average transaction value
Avg_transactions_value_by_age=digital_wallet_df.groupby(by=["Age"]).agg({"Avg_Transaction_Value":"mean"}).reset_index()
Avg_transactions_value_by_age=Avg_transactions_by_age.sort_values(by=["Avg_Transaction_Value"],ascending=[False]).reset_index(drop=True)
Avg_transactions_value_by_age

KeyError: 'Avg_Transaction_Value'

In [ ]:
#Age wise average Max_Transaction_Value
Avg_Max_Transaction_Value_age=digital_wallet_df.groupby(by=["Age"]).agg({"Max_Transaction_Value":"mean"}).reset_index()
Avg_Max_Transaction_Value_age=Avg_Max_Transaction_Value_age.sort_values(by=["Max_Transaction_Value"],ascending=[False]).reset_index(drop=True)
Avg_Max_Transaction_Value_age

In [ ]:
#Age wise average Min_Transaction_Value
Avg_Min_Transaction_Value=digital_wallet_df.groupby(by=["Age"]).agg({"Min_Transaction_Value":"mean"}).reset_index()
Avg_Min_Transaction_Value=Avg_Min_Transaction_Value.sort_values(by=["Min_Transaction_Value"],ascending=[False]).reset_index(drop=True)
Avg_Min_Transaction_Value

In [25]:
#Age wise Total_Spent
Avg_Total_Spent=digital_wallet_df.groupby(by=["Age"]).agg({"Total_Spent":"mean"}).reset_index()
Avg_Total_Spent=Avg_Total_Spent.sort_values(by=["Total_Spent"],ascending=[False]).reset_index(drop=True)
Avg_Total_Spent["Total_Spent"]=Avg_Total_Spent["Total_Spent"].astype('int')
Avg_Total_Spent

    Age  Total_Spent
0    58      6270105
1    33      5762359
2    45      5714187
3    37      5628114
4    46      5556225
5    68      5542417
6    44      5529124
7    23      5517417
8    66      5497115
9    47      5462226
10   24      5347111
11   22      5336591
12   60      5333026
13   27      5322483
14   52      5297163
15   59      5276121
16   51      5239969
17   64      5235655
18   20      5217559
19   34      5212141
20   18      5170944
21   29      5143643
22   43      5067670
23   21      5019971
24   17      4987216
25   39      4950500
26   61      4917988
27   41      4914193
28   50      4910177
29   48      4908548
30   40      4899284
31   32      4885172
32   54      4824122
33   69      4823041
34   55      4806017
35   57      4801155
36   31      4799649
37   42      4784122
38   56      4728742
39   30      4717822
40   35      4655885
41   65      4654366
42   28      4641340
43   25      4640793
44   36      4616880
45   53      4578217
46   63      4547113
47   67      4525570
48   26      4494203
49   38      4485019
50   62      4463808
51   49      4313596
52   19      4223223
53   16      4171936

In [26]:
#Age wise Active_Days
Avg_Active_Days=digital_wallet_df.groupby(by=["Age"]).agg({"Active_Days":"mean"}).reset_index()
Avg_Active_Days=Avg_Active_Days.sort_values(by=["Active_Days"],ascending=[False]).reset_index(drop=True)
Avg_Active_Days["Active_Days"]=Avg_Active_Days["Active_Days"].astype('int')
Avg_Active_Days

    Age  Active_Days
0    43          196
1    18          195
2    66          194
3    40          193
4    42          193
5    65          193
6    50          192
7    25          192
8    29          190
9    49          189
10   63          189
11   38          188
12   57          187
13   34          187
14   58          186
15   19          186
16   47          186
17   27          186
18   35          186
19   59          185
20   21          185
21   67          184
22   48          184
23   41          184
24   17          184
25   54          184
26   62          183
27   33          183
28   45          183
29   37          182
30   44          182
31   30          181
32   69          181
33   26          181
34   16          180
35   28          179
36   36          179
37   31          179
38   39          178
39   64          177
40   51          176
41   68          176
42   22          173
43   56          173
44   55          173
45   52          172
46   20          171
47   60          171
48   46          170
49   61          169
50   23          166
51   32          164
52   24          161
53   53          158

In [27]:
#Age wise Loyalty_Points_Earned
Avg_Loyalty_Points_Earned=digital_wallet_df.groupby(by=["Age"]).agg({"Loyalty_Points_Earned":"mean"}).reset_index()
Avg_Loyalty_Points_Earned=Avg_Loyalty_Points_Earned.sort_values(by=["Loyalty_Points_Earned"],ascending=[False]).reset_index(drop=True)
Avg_Loyalty_Points_Earned

    Age  Loyalty_Points_Earned
0    64            2742.281046
1    29            2699.408333
2    40            2695.708029
3    58            2678.666667
4    41            2677.845070
5    52            2673.833333
6    56            2665.621849
7    20            2662.144000
8    21            2655.238095
9    62            2613.796296
10   38            2604.275362
11   16            2595.604839
12   69            2566.013423
13   23            2561.390071
14   50            2559.128378
15   47            2558.105263
16   36            2556.076389
17   60            2549.706667
18   26            2540.320896
19   55            2539.561151
20   51            2526.381679
21   66            2525.484375
22   34            2515.373016
23   53            2504.245902
24   46            2503.233010
25   33            2491.008403
26   30            2488.862595
27   57            2480.466667
28   32            2471.340000
29   17            2470.795455
30   22            2459.468750
31   44            2458.335766
32   43            2458.000000
33   39            2453.880952
34   54            2445.536000
35   25            2440.516949
36   65            2437.913043
37   61            2431.871795
38   59            2427.587302
39   45            2421.820312
40   49            2417.954198
41   68            2410.388430
42   28            2408.787879
43   42            2381.867925
44   19            2381.171642
45   18            2378.782946
46   37            2378.154930
47   67            2376.433333
48   63            2372.123894
49   27            2357.090909
50   35            2339.559701
51   31            2338.706897
52   24            2338.393443
53   48            2209.000000

In [28]:
#Age wise Referral_Count
Avg_Referral_Count=digital_wallet_df.groupby(by=["Age"]).agg({"Referral_Count":"mean"}).reset_index()
Avg_Referral_Count=Avg_Referral_Count.sort_values(by=["Referral_Count"],ascending=[False]).reset_index(drop=True)
Avg_Referral_Count["Referral_Count"]=Avg_Referral_Count["Referral_Count"].astype('int')
Avg_Referral_Count

    Age  Referral_Count
0    21              28
1    39              27
2    45              27
3    17              26
4    16              26
5    19              26
6    43              26
7    65              26
8    24              25
9    60              25
10   56              25
11   59              25
12   40              25
13   27              25
14   18              25
15   64              25
16   62              25
17   48              25
18   41              25
19   25              25
20   22              25
21   36              25
22   52              25
23   26              25
24   28              25
25   30              25
26   23              24
27   31              24
28   38              24
29   66              24
30   50              24
31   46              24
32   58              24
33   47              24
34   67              24
35   35              24
36   49              24
37   55              23
38   42              23
39   51              23
40   34              23
41   63              23
42   44              23
43   33              23
44   68              23
45   54              23
46   20              23
47   61              23
48   53              23
49   37              23
50   57              23
51   69              22
52   29              22
53   32              22

In [29]:
#Age wise Cashback_Received
Avg_Cashback_Received=digital_wallet_df.groupby(by=["Age"]).agg({"Cashback_Received":"mean"}).reset_index()
Avg_Cashback_Received=Avg_Cashback_Received.sort_values(by=["Cashback_Received"],ascending=[False]).reset_index(drop=True)
# Avg_Cashback_Received["Referral_Count"]=Avg_Cashback_Received["Cashback_Received"].astype('int')
Avg_Cashback_Received

    Age  Cashback_Received
0    62        2726.234548
1    45        2701.005017
2    49        2676.633872
3    69        2660.582400
4    38        2634.231422
5    32        2631.897919
6    68        2625.400642
7    61        2623.885112
8    33        2612.149307
9    36        2606.093688
10   22        2590.876179
11   17        2589.716456
12   28        2584.564925
13   56        2560.499925
14   23        2558.337746
15   59        2555.661960
16   16        2549.487190
17   55        2539.570138
18   21        2535.223257
19   54        2534.780278
20   40        2531.778686
21   47        2524.218386
22   31        2523.665057
23   41        2520.629874
24   43        2519.425219
25   60        2518.522688
26   19        2517.428071
27   34        2509.129406
28   48        2497.722782
29   51        2497.309220
30   39        2496.662178
31   27        2496.212979
32   57        2483.556859
33   30        2480.526221
34   63        2471.786071
35   18        2453.568097
36   65        2451.813243
37   35        2450.310546
38   25        2444.266004
39   20        2435.326743
40   64        2431.651785
41   37        2426.835534
42   44        2403.656470
43   26        2389.681627
44   53        2360.060745
45   50        2345.694354
46   67        2340.891580
47   66        2340.270330
48   29        2335.195950
49   52        2324.176931
50   24        2298.215341
51   46        2294.985866
52   42        2260.088592
53   58        2109.723136

In [30]:
#Age wise Support_Tickets_Raised
Avg_Support_Tickets_Raised=digital_wallet_df.groupby(by=["Age"]).agg({"Support_Tickets_Raised":"mean"}).reset_index()
Avg_Support_Tickets_Raised=Avg_Support_Tickets_Raised.sort_values(by=["Support_Tickets_Raised"],ascending=[False]).reset_index(drop=True)
Avg_Support_Tickets_Raised["Support_Tickets_Raised"]=Avg_Support_Tickets_Raised["Support_Tickets_Raised"].astype('int')
Avg_Support_Tickets_Raised

    Age  Support_Tickets_Raised
0    63                      11
1    44                      11
2    31                      10
3    18                      10
4    57                      10
5    64                      10
6    68                      10
7    20                      10
8    65                      10
9    62                      10
10   30                      10
11   22                      10
12   55                      10
13   21                      10
14   36                      10
15   56                      10
16   24                      10
17   25                      10
18   60                      10
19   58                      10
20   23                      10
21   28                      10
22   61                      10
23   66                      10
24   51                      10
25   53                      10
26   46                      10
27   40                      10
28   38                      10
29   16                       9
30   69                       9
31   29                       9
32   52                       9
33   48                       9
34   33                       9
35   67                       9
36   54                       9
37   49                       9
38   26                       9
39   17                       9
40   27                       9
41   41                       9
42   59                       9
43   43                       9
44   50                       9
45   37                       9
46   42                       9
47   45                       9
48   19                       9
49   32                       9
50   47                       9
51   35                       9
52   39                       9
53   34                       9

In [31]:
#Age wise Issue_Resolution_Time
Avg_Issue_Resolution_Time=digital_wallet_df.groupby(by=["Age"]).agg({"Issue_Resolution_Time":"mean"}).reset_index()
Avg_Issue_Resolution_Time=Avg_Issue_Resolution_Time.sort_values(by=["Issue_Resolution_Time"],ascending=[False]).reset_index(drop=True)
#Avg_Support_Tickets_Raised["Support_Tickets_Raised"]=Avg_Support_Tickets_Raised["Support_Tickets_Raised"].astype('int')
Avg_Issue_Resolution_Time

    Age  Issue_Resolution_Time
0    33              41.841457
1    21              40.023326
2    67              39.503642
3    39              39.197074
4    57              39.012988
5    31              38.535863
6    25              38.510144
7    36              38.349908
8    43              38.260648
9    62              38.218551
10   38              37.997772
11   50              37.952452
12   17              37.937989
13   22              37.904460
14   19              37.873040
15   16              37.867628
16   30              37.797212
17   66              37.604739
18   56              37.572680
19   37              37.517230
20   65              37.272596
21   64              37.205906
22   52              37.156127
23   48              37.033319
24   29              36.868857
25   42              36.866470
26   32              36.736832
27   24              36.658469
28   26              36.591251
29   28              36.456364
30   46              36.432463
31   63              36.238400
32   51              36.095862
33   41              35.894664
34   68              35.833252
35   54              35.697263
36   49              35.383950
37   18              35.133498
38   40              35.129879
39   60              35.073316
40   45              34.869822
41   59              34.791530
42   27              34.790201
43   61              34.770578
44   47              34.692546
45   69              34.568492
46   44              34.566024
47   23              34.323054
48   20              34.252200
49   53              34.152917
50   35              33.820206
51   34              33.354628
52   58              33.287878
53   55              32.158954

In [32]:
#Age wise Customer_Satisfaction_Score
Avg_Customer_Satisfaction_Score=digital_wallet_df.groupby(by=["Age"]).agg({"Customer_Satisfaction_Score":"mean"}).reset_index()
Avg_Customer_Satisfaction_Score=Avg_Customer_Satisfaction_Score.sort_values(by=["Customer_Satisfaction_Score"],ascending=[False]).reset_index(drop=True)
Avg_Customer_Satisfaction_Score["Customer_Satisfaction_Score"]=Avg_Customer_Satisfaction_Score["Customer_Satisfaction_Score"].astype('int')
Avg_Customer_Satisfaction_Score

    Age  Customer_Satisfaction_Score
0    42                            5
1    23                            5
2    26                            5
3    33                            5
4    32                            5
5    17                            5
6    60                            5
7    59                            5
8    43                            5
9    16                            5
10   69                            5
11   47                            5
12   37                            5
13   31                            5
14   39                            5
15   58                            5
16   66                            5
17   22                            5
18   48                            5
19   49                            5
20   55                            5
21   20                            5
22   53                            5
23   52                            5
24   35                            5
25   29                            5
26   50                            5
27   67                            5
28   51                            5
29   38                            5
30   30                            5
31   64                            5
32   57                            5
33   68                            5
34   44                            5
35   18                            5
36   34                            5
37   27                            5
38   40                            5
39   45                            5
40   28                            5
41   54                            5
42   41                            5
43   19                            5
44   63                            5
45   25                            5
46   62                            5
47   21                            5
48   65                            5
49   36                            5
50   24                            5
51   61                            5
52   46                            4
53   56                            4

In [33]:
#Age wise LTV
Avg_LTV=digital_wallet_df.groupby(by=["Age"]).agg({"LTV":"mean"}).reset_index()
Avg_LTV=Avg_LTV.sort_values(by=["LTV"],ascending=[False]).reset_index(drop=True)
#Avg_Customer_Satisfaction_Score["Customer_Satisfaction_Score"]=Avg_Customer_Satisfaction_Score["LTV"].astype('int')
Avg_LTV

    Age            LTV
0    58  639330.637017
1    33  588180.802995
2    45  582972.819678
3    37  574306.484294
4    46  566834.918398
5    68  565481.218807
6    44  564364.556097
7    23  564014.414226
8    66  561654.107593
9    47  558168.831750
10   24  545992.140097
11   60  545478.138850
12   22  545404.489787
13   27  543625.779791
14   52  541935.942350
15   59  539514.145884
16   64  535800.318454
17   51  535637.740505
18   20  533752.214723
19   34  532720.533604
20   18  528554.656853
21   29  526343.100394
22   43  518768.131297
23   21  514105.851268
24   17  510816.865453
25   39  507114.218457
26   41  503335.883670
27   50  502889.489670
28   61  502793.402914
29   48  502158.703968
30   40  501959.059444
31   32  500179.293426
32   69  494061.632897
33   54  493673.540727
34   55  492363.638419
35   57  491522.237796
36   31  491482.235190
37   42  490410.084542
38   56  484428.583914
39   30  483431.970149
40   35  476948.466087
41   65  476914.366995
42   25  475517.901238
43   28  475464.606884
44   36  473239.482040
45   53  469494.514995
46   63  465833.871324
47   67  464012.828436
48   26  461784.472382
49   38  460291.211558
50   62  458034.176060
51   49  442822.850884
52   19  433725.942816
53   16  429481.108437

#Location

In [34]:
#location wise total_transactions
total_transactions_by_location=digital_wallet_df.groupby(by=["Location"]).agg({"Total_Transactions":"mean"}).reset_index()
total_transactions_by_location=total_transactions_by_location.sort_values(by=["Total_Transactions"],ascending=[False])
total_transactions_by_location

   Location  Total_Transactions
0     Rural          508.208045
1  Suburban          498.852155
2     Urban          496.721284

In [35]:
#location wise Avg_Transaction_Value
Avg_Transaction_Value_by_location=digital_wallet_df.groupby(by=["Location"]).agg({"Avg_Transaction_Value":"mean"}).reset_index()
Avg_Transaction_Value_by_location=Avg_Transaction_Value_by_location.sort_values(by=["Avg_Transaction_Value"],ascending=[False])
Avg_Transaction_Value_by_location

   Location  Avg_Transaction_Value
1  Suburban           10145.350643
2     Urban            9877.087613
0     Rural            9819.058570

In [36]:
#location wise Max_Transaction_Value
Avg_Max_Transaction_Value=digital_wallet_df.groupby(by=["Location"]).agg({"Max_Transaction_Value":"mean"}).reset_index()
Avg_Max_Transaction_Value=Avg_Max_Transaction_Value.sort_values(by=["Max_Transaction_Value"],ascending=[False])
Avg_Max_Transaction_Value

   Location  Max_Transaction_Value
2     Urban           30515.767303
1  Suburban           30290.292881
0     Rural           29663.650966

In [37]:
#location wise Min_Transaction_Value
Avg_Min_Transaction_Value=digital_wallet_df.groupby(by=["Location"]).agg({"Min_Transaction_Value":"mean"}).reset_index()
Avg_Min_Transaction_Value=Avg_Min_Transaction_Value.sort_values(by=["Min_Transaction_Value"],ascending=[False])
Avg_Min_Transaction_Value

   Location  Min_Transaction_Value
2     Urban            3008.356602
1  Suburban            3005.587963
0     Rural            2929.972821

In [38]:
#location wise Total_Spent
Avg_Total_Spent=digital_wallet_df.groupby(by=["Location"]).agg({"Total_Spent":"mean"}).reset_index()
Avg_Total_Spent=Avg_Total_Spent.sort_values(by=["Total_Spent"],ascending=[False])
Avg_Total_Spent["Total_Spent"]=Avg_Total_Spent["Total_Spent"].astype('int')
Avg_Total_Spent

   Location  Total_Spent
1  Suburban      5086788
0     Rural      4961601
2     Urban      4958438

In [39]:
digital_wallet_df.columns

Index(['Customer_ID', 'Age', 'Location', 'Income_Level', 'Total_Transactions',
       'Avg_Transaction_Value', 'Max_Transaction_Value',
       'Min_Transaction_Value', 'Total_Spent', 'Active_Days',
       'Last_Transaction_Days_Ago', 'Loyalty_Points_Earned', 'Referral_Count',
       'Cashback_Received', 'App_Usage_Frequency', 'Preferred_Payment_Method',
       'Support_Tickets_Raised', 'Issue_Resolution_Time',
       'Customer_Satisfaction_Score', 'LTV'],
      dtype='object')

In [40]:
#location wise Active_Days
Avg_Active_Days=digital_wallet_df.groupby(by=["Location"]).agg({"Active_Days":"mean"}).reset_index()
Avg_Active_Days=Avg_Active_Days.sort_values(by=["Active_Days"],ascending=[False])
Avg_Active_Days["Active_Days"]=Avg_Active_Days["Active_Days"].astype('int')
Avg_Active_Days

   Location  Active_Days
1  Suburban          182
0     Rural          182
2     Urban          180

In [41]:
#location wise Loyalty_Points_Earned
Avg_Loyalty_Points_Earned=digital_wallet_df.groupby(by=["Location"]).agg({"Loyalty_Points_Earned":"mean"}).reset_index()
Avg_Loyalty_Points_Earned=Avg_Loyalty_Points_Earned.sort_values(by=["Loyalty_Points_Earned"],ascending=[False])
Avg_Loyalty_Points_Earned["Loyalty_Points_Earned"]=Avg_Loyalty_Points_Earned["Loyalty_Points_Earned"].astype('int')
Avg_Loyalty_Points_Earned

   Location  Loyalty_Points_Earned
1  Suburban                   2507
2     Urban                   2506
0     Rural                   2490

In [42]:
#location wise Referral_Count
Avg_Referral_Count=digital_wallet_df.groupby(by=["Location"]).agg({"Referral_Count":"mean"}).reset_index()
Avg_Referral_Count=Avg_Referral_Count.sort_values(by=["Referral_Count"],ascending=[False])
Avg_Referral_Count["Referral_Count"]=Avg_Referral_Count["Referral_Count"].astype('int')
Avg_Referral_Count

   Location  Referral_Count
1  Suburban              24
2     Urban              24
0     Rural              24

In [43]:
#location wise Cashback_Received
Avg_Cashback_Received=digital_wallet_df.groupby(by=["Location"]).agg({"Cashback_Received":"mean"}).reset_index()
Avg_Cashback_Received=Avg_Cashback_Received.sort_values(by=["Cashback_Received"],ascending=[False])
#Avg_Referral_Count["Referral_Count"]=Avg_Referral_Count["Referral_Count"].astype('int')
Avg_Cashback_Received

   Location  Cashback_Received
2     Urban        2521.937422
1  Suburban        2488.171969
0     Rural        2478.879084

In [44]:
#location wise Support_Tickets_Raised
Avg_Support_Tickets_Raised=digital_wallet_df.groupby(by=["Location"]).agg({"Support_Tickets_Raised":"mean"}).reset_index()
Avg_Support_Tickets_Raised=Avg_Support_Tickets_Raised.sort_values(by=["Support_Tickets_Raised"],ascending=[False])
Avg_Support_Tickets_Raised["Support_Tickets_Raised"]=Avg_Support_Tickets_Raised["Support_Tickets_Raised"].astype('int')
Avg_Support_Tickets_Raised

   Location  Support_Tickets_Raised
0     Rural                      10
2     Urban                      10
1  Suburban                       9

In [45]:
#location wise Issue_Resolution_Time
Avg_Issue_Resolution_Time=digital_wallet_df.groupby(by=["Location"]).agg({"Issue_Resolution_Time":"mean"}).reset_index()
Avg_Issue_Resolution_Time=Avg_Issue_Resolution_Time.sort_values(by=["Issue_Resolution_Time"],ascending=[False])
#Avg_Issue_Resolution_Time["Issue_Resolution_Time"]=Avg_Issue_Resolution_Time["Issue_Resolution_Time"].astype('int')
Avg_Issue_Resolution_Time

   Location  Issue_Resolution_Time
0     Rural              36.709165
1  Suburban              36.484674
2     Urban              36.393587

In [46]:
#location wise Customer_Satisfaction_Score
Avg_Customer_Satisfaction_Score=digital_wallet_df.groupby(by=["Location"]).agg({"Customer_Satisfaction_Score":"mean"}).reset_index()
Avg_Customer_Satisfaction_Score=Avg_Customer_Satisfaction_Score.sort_values(by=["Customer_Satisfaction_Score"],ascending=[False])
Avg_Customer_Satisfaction_Score["Customer_Satisfaction_Score"]=Avg_Customer_Satisfaction_Score["Customer_Satisfaction_Score"].astype('int')
Avg_Customer_Satisfaction_Score

   Location  Customer_Satisfaction_Score
2     Urban                            5
1  Suburban                            5
0     Rural                            5

In [47]:
#location wise LTV
Avg_LTV=digital_wallet_df.groupby(by=["Location"]).agg({"LTV":"mean"}).reset_index()
Avg_LTV=Avg_LTV.sort_values(by=["LTV"],ascending=[False])
#Avg_LTV["LTV"]=Avg_LTV["LTV"].astype('int')
Avg_LTV

   Location            LTV
1  Suburban  520381.032606
0     Rural  507813.534441
2     Urban  507638.990963

#income

In [48]:
#Avg transactions by income level
Avg_no_of_transaction_by_income_level=digital_wallet_df.groupby(by=["Income_Level"]).agg({"Total_Transactions":"mean"}).reset_index()
Avg_no_of_transaction_by_income_level.sort_values(by=["Total_Transactions"],ascending=[False])
Avg_no_of_transaction_by_income_level["Total_Transactions"]=Avg_no_of_transaction_by_income_level["Total_Transactions"].astype('int')
Avg_no_of_transaction_by_income_level

  Income_Level  Total_Transactions
0         High                 496
1          Low                 495
2       Middle                 511

In [49]:
#Avg transaction value by income level
Avg_transaction_by_income_level=digital_wallet_df.groupby(by=["Income_Level"]).agg({"Avg_Transaction_Value":"mean"}).reset_index()
Avg_transaction_by_income_level.sort_values(by=["Avg_Transaction_Value"],ascending=[False])

  Income_Level  Avg_Transaction_Value
1          Low           10013.851622
2       Middle            9981.673123
0         High            9843.180522

In [50]:
#Avg max transaction values by income level
Avg_max_transaction_value_by_income_level=digital_wallet_df.groupby(by=["Income_Level"]).agg({"Max_Transaction_Value":"mean"}).reset_index()
Avg_max_transaction_value_by_income_level.sort_values(by=["Max_Transaction_Value"],ascending=[False])

  Income_Level  Max_Transaction_Value
1          Low           30478.246349
2       Middle           30133.738099
0         High           29866.049775

In [51]:
#Avg min transaction values by income level
Avg_min_transaction_value_by_income_level=digital_wallet_df.groupby(by=["Income_Level"]).agg({"Min_Transaction_Value":"mean"}).reset_index()
Avg_min_transaction_value_by_income_level.sort_values(by=["Min_Transaction_Value"],ascending=[False])

  Income_Level  Min_Transaction_Value
1          Low            2993.559882
2       Middle            2986.306089
0         High            2964.523466

In [52]:
#Avg Total spent by income level
Avg_min_transaction_value_by_income_level=digital_wallet_df.groupby(by=["Income_Level"]).agg({"Total_Spent":"mean"}).reset_index()
Avg_min_transaction_value_by_income_level=Avg_min_transaction_value_by_income_level.sort_values(by=["Total_Spent"],ascending=[False])
Avg_min_transaction_value_by_income_level["Total_Spent"]=Avg_min_transaction_value_by_income_level["Total_Spent"].astype('int')
Avg_min_transaction_value_by_income_level

  Income_Level  Total_Spent
2       Middle      5111000
1          Low      4983635
0         High      4907123

In [53]:
#Avg Active days by income level
Avg_Active_Days_by_income_level=digital_wallet_df.groupby(by=["Income_Level"]).agg({"Active_Days":"mean"}).reset_index()
Avg_Active_Days_by_income_level=Avg_Active_Days_by_income_level.sort_values(by=["Active_Days"],ascending=[False])
Avg_Active_Days_by_income_level["Active_Days"]=Avg_Active_Days_by_income_level["Active_Days"].astype('int')
Avg_Active_Days_by_income_level

  Income_Level  Active_Days
2       Middle          183
1          Low          181
0         High          180

In [54]:
#Avg Loyalty_Points_Earned by income level
Avg_Loyalty_Points_Earned_by_income_level=digital_wallet_df.groupby(by=["Income_Level"]).agg({"Loyalty_Points_Earned":"mean"}).reset_index()
Avg_Loyalty_Points_Earned_by_income_level=Avg_Loyalty_Points_Earned_by_income_level.sort_values(by=["Loyalty_Points_Earned"],ascending=[False])
Avg_Loyalty_Points_Earned_by_income_level["Loyalty_Points_Earned"]=Avg_Loyalty_Points_Earned_by_income_level["Loyalty_Points_Earned"].astype('int')
Avg_Loyalty_Points_Earned_by_income_level

  Income_Level  Loyalty_Points_Earned
1          Low                   2521
2       Middle                   2512
0         High                   2470

In [55]:
#Avg Referral_Count by income level
Avg_Referral_Count_by_income_level=digital_wallet_df.groupby(by=["Income_Level"]).agg({"Referral_Count":"mean"}).reset_index()
Avg_Referral_Count_by_income_level=Avg_Referral_Count_by_income_level.sort_values(by=["Referral_Count"],ascending=[False])
Avg_Referral_Count_by_income_level["Referral_Count"]=Avg_Referral_Count_by_income_level["Referral_Count"].astype('int')
Avg_Referral_Count_by_income_level

  Income_Level  Referral_Count
0         High              24
2       Middle              24
1          Low              24

In [56]:
#Avg Cashback_Received by income level
Avg_Cashback_Received_by_income_level=digital_wallet_df.groupby(by=["Income_Level"]).agg({"Cashback_Received":"mean"}).reset_index()
Avg_Cashback_Received_by_income_level=Avg_Cashback_Received_by_income_level.sort_values(by=["Cashback_Received"],ascending=[False])
Avg_Cashback_Received_by_income_level

  Income_Level  Cashback_Received
2       Middle        2503.467522
1          Low        2496.859810
0         High        2488.964909

In [57]:
#Avg Support_Tickets_Raised by income level
Avg_Support_Tickets_Raised_by_income_level=digital_wallet_df.groupby(by=["Income_Level"]).agg({"Support_Tickets_Raised":"mean"}).reset_index()
Avg_Support_Tickets_Raised_by_income_level=Avg_Support_Tickets_Raised_by_income_level.sort_values(by=["Support_Tickets_Raised"],ascending=[False])
Avg_Support_Tickets_Raised_by_income_level["Support_Tickets_Raised"]=Avg_Support_Tickets_Raised_by_income_level["Support_Tickets_Raised"].astype('int')
Avg_Support_Tickets_Raised_by_income_level

  Income_Level  Support_Tickets_Raised
0         High                      10
2       Middle                      10
1          Low                       9

In [58]:
#Avg Issue_Resolution_Time by income level
Avg_Issue_Resolution_Time_by_income_level=digital_wallet_df.groupby(by=["Income_Level"]).agg({"Issue_Resolution_Time":"mean"}).reset_index()
Avg_Issue_Resolution_Time_by_income_level=Avg_Issue_Resolution_Time_by_income_level.sort_values(by=["Issue_Resolution_Time"],ascending=[False])
Avg_Issue_Resolution_Time_by_income_level

  Income_Level  Issue_Resolution_Time
0         High              36.831720
1          Low              36.437171
2       Middle              36.323903

In [59]:
#Avg Customer_Satisfaction_Score by income level
Avg_Customer_Satisfaction_Score_by_income_level=digital_wallet_df.groupby(by=["Income_Level"]).agg({"Customer_Satisfaction_Score":"mean"}).reset_index()
Avg_Customer_Satisfaction_Score_by_income_level=Avg_Customer_Satisfaction_Score_by_income_level.sort_values(by=["Customer_Satisfaction_Score"],ascending=[False])
Avg_Customer_Satisfaction_Score_by_income_level["Customer_Satisfaction_Score"]=Avg_Customer_Satisfaction_Score_by_income_level["Customer_Satisfaction_Score"].astype('int')
Avg_Customer_Satisfaction_Score_by_income_level

  Income_Level  Customer_Satisfaction_Score
2       Middle                            5
0         High                            5
1          Low                            5

In [60]:
#Avg LTV by income level
Avg_LTV_by_income_level=digital_wallet_df.groupby(by=["Income_Level"]).agg({"LTV":"mean"}).reset_index()
Avg_LTV_by_income_level=Avg_LTV_by_income_level.sort_values(by=["LTV"],ascending=[False])
Avg_LTV_by_income_level

  Income_Level            LTV
2       Middle  522912.135301
1          Low  510053.529384
0         High  502359.180141

#App_Usage_Frequency

In [61]:
#Avg transactions by App_Usage_Frequency
Avg_transaction_by_App_Usage_Frequency=digital_wallet_df.groupby(["App_Usage_Frequency"]).agg({"Total_Transactions":"mean"}).reset_index()
Avg_transaction_by_App_Usage_Frequency=Avg_transaction_by_App_Usage_Frequency.sort_values(by=["Total_Transactions"],ascending=[False])
Avg_transaction_by_App_Usage_Frequency["Total_Transactions"]=Avg_transaction_by_App_Usage_Frequency["Total_Transactions"].astype('int')
Avg_transaction_by_App_Usage_Frequency

  App_Usage_Frequency  Total_Transactions
2              Weekly                 502
1             Monthly                 501
0               Daily                 500

In [62]:
#Avg_Transaction_Value by App_Usage_Frequency
Avg_Avg_Transaction_Value_by_App_Usage_Frequency=digital_wallet_df.groupby(["App_Usage_Frequency"]).agg({"Avg_Transaction_Value":"mean"}).reset_index()
Avg_Avg_Transaction_Value_by_App_Usage_Frequency=Avg_Avg_Transaction_Value_by_App_Usage_Frequency.sort_values(by=["Avg_Transaction_Value"],ascending=[False])
Avg_Avg_Transaction_Value_by_App_Usage_Frequency

  App_Usage_Frequency  Avg_Transaction_Value
1             Monthly            9991.619146
2              Weekly            9983.806147
0               Daily            9865.724676

In [63]:
#Avg Max_Transaction_Value by App_Usage_Frequency
Avg_Max_Transaction_Value_by_App_Usage_Frequency=digital_wallet_df.groupby(["App_Usage_Frequency"]).agg({"Max_Transaction_Value":"mean"}).reset_index()
Avg_Max_Transaction_Value_by_App_Usage_Frequency=Avg_Max_Transaction_Value_by_App_Usage_Frequency.sort_values(by=["Max_Transaction_Value"],ascending=[False])
Avg_Max_Transaction_Value_by_App_Usage_Frequency

  App_Usage_Frequency  Max_Transaction_Value
2              Weekly           30538.820635
0               Daily           30053.237589
1             Monthly           29888.159781

In [64]:
#Avg Min_Transaction_Value by App_Usage_Frequency
Avg_Min_Transaction_Value_by_App_Usage_Frequency=digital_wallet_df.groupby(["App_Usage_Frequency"]).agg({"Min_Transaction_Value":"mean"}).reset_index()
Avg_Min_Transaction_Value_by_App_Usage_Frequency=Avg_Min_Transaction_Value_by_App_Usage_Frequency.sort_values(by=["Min_Transaction_Value"],ascending=[False])
Avg_Min_Transaction_Value_by_App_Usage_Frequency

  App_Usage_Frequency  Min_Transaction_Value
2              Weekly            2992.772785
1             Monthly            2992.641251
0               Daily            2959.416654

In [65]:
#Avg Total_Spent by App_Usage_Frequency
Avg_Total_Spent_by_App_Usage_Frequency=digital_wallet_df.groupby(["App_Usage_Frequency"]).agg({"Total_Spent":"mean"}).reset_index()
Avg_Total_Spent_by_App_Usage_Frequency=Avg_Total_Spent_by_App_Usage_Frequency.sort_values(by=["Total_Spent"],ascending=[False])
Avg_Total_Spent_by_App_Usage_Frequency["Total_Spent"]=Avg_Total_Spent_by_App_Usage_Frequency["Total_Spent"].astype('int')
Avg_Total_Spent_by_App_Usage_Frequency

  App_Usage_Frequency  Total_Spent
2              Weekly      5022671
1             Monthly      5011513
0               Daily      4972134

In [66]:
#Avg Active_Days by App_Usage_Frequency
Avg_Active_Days_by_App_Usage_Frequency=digital_wallet_df.groupby(["App_Usage_Frequency"]).agg({"Active_Days":"mean"}).reset_index()
Avg_Active_Days_by_App_Usage_Frequency=Avg_Active_Days_by_App_Usage_Frequency.sort_values(by=["Active_Days"],ascending=[False])
Avg_Active_Days_by_App_Usage_Frequency["Active_Days"]=Avg_Active_Days_by_App_Usage_Frequency["Active_Days"].astype('int')
Avg_Active_Days_by_App_Usage_Frequency

  App_Usage_Frequency  Active_Days
1             Monthly          184
2              Weekly          180
0               Daily          180

In [67]:
#Avg Loyalty_Points_Earned by App_Usage_Frequency
Avg_Loyalty_Points_Earned_by_App_Usage_Frequency=digital_wallet_df.groupby(["App_Usage_Frequency"]).agg({"Loyalty_Points_Earned":"mean"}).reset_index()
Avg_Loyalty_Points_Earned_by_App_Usage_Frequency=Avg_Loyalty_Points_Earned_by_App_Usage_Frequency.sort_values(by=["Loyalty_Points_Earned"],ascending=[False])
Avg_Loyalty_Points_Earned_by_App_Usage_Frequency["Loyalty_Points_Earned"]=Avg_Loyalty_Points_Earned_by_App_Usage_Frequency["Loyalty_Points_Earned"].astype('int')
Avg_Loyalty_Points_Earned_by_App_Usage_Frequency

  App_Usage_Frequency  Loyalty_Points_Earned
2              Weekly                   2539
1             Monthly                   2507
0               Daily                   2457

In [68]:
#Avg Referral_Count by App_Usage_Frequency
Avg_Referral_Count_by_App_Usage_Frequency=digital_wallet_df.groupby(["App_Usage_Frequency"]).agg({"Referral_Count":"mean"}).reset_index()
Avg_Referral_Count_by_App_Usage_Frequency=Avg_Referral_Count_by_App_Usage_Frequency.sort_values(by=["Referral_Count"],ascending=[False])
Avg_Referral_Count_by_App_Usage_Frequency["Referral_Count"]=Avg_Referral_Count_by_App_Usage_Frequency["Referral_Count"].astype('int')
Avg_Referral_Count_by_App_Usage_Frequency

  App_Usage_Frequency  Referral_Count
2              Weekly              25
1             Monthly              24
0               Daily              24

In [69]:
#Avg Cashback_Received by App_Usage_Frequency
Avg_Cashback_Received_by_App_Usage_Frequency=digital_wallet_df.groupby(["App_Usage_Frequency"]).agg({"Cashback_Received":"mean"}).reset_index()
Avg_Cashback_Received_by_App_Usage_Frequency=Avg_Cashback_Received_by_App_Usage_Frequency.sort_values(by=["Cashback_Received"],ascending=[False])
Avg_Cashback_Received_by_App_Usage_Frequency

  App_Usage_Frequency  Cashback_Received
2              Weekly        2542.186003
0               Daily        2490.050246
1             Monthly        2457.464531

In [70]:
#Avg Support_Tickets_Raised by App_Usage_Frequency
Avg_Support_Tickets_Raised_by_App_Usage_Frequency=digital_wallet_df.groupby(["App_Usage_Frequency"]).agg({"Support_Tickets_Raised":"mean"}).reset_index()
Avg_Support_Tickets_Raised_by_App_Usage_Frequency=Avg_Support_Tickets_Raised_by_App_Usage_Frequency.sort_values(by=["Support_Tickets_Raised"],ascending=[False])
Avg_Support_Tickets_Raised_by_App_Usage_Frequency["Support_Tickets_Raised"]=Avg_Support_Tickets_Raised_by_App_Usage_Frequency["Support_Tickets_Raised"].astype('int')
Avg_Support_Tickets_Raised_by_App_Usage_Frequency

  App_Usage_Frequency  Support_Tickets_Raised
2              Weekly                      10
1             Monthly                       9
0               Daily                       9

In [71]:
#Avg Issue_Resolution_Time by App_Usage_Frequency
Avg_Issue_Resolution_Time_by_App_Usage_Frequency=digital_wallet_df.groupby(["App_Usage_Frequency"]).agg({"Issue_Resolution_Time":"mean"}).reset_index()
Avg_Issue_Resolution_Time_by_App_Usage_Frequency=Avg_Issue_Resolution_Time_by_App_Usage_Frequency.sort_values(by=["Issue_Resolution_Time"],ascending=[False])
Avg_Issue_Resolution_Time_by_App_Usage_Frequency

  App_Usage_Frequency  Issue_Resolution_Time
1             Monthly              36.965874
2              Weekly              36.941045
0               Daily              35.683972

In [72]:
#Avg Customer_Satisfaction_Score by App_Usage_Frequency
Avg_Customer_Satisfaction_Score_by_App_Usage_Frequency=digital_wallet_df.groupby(["App_Usage_Frequency"]).agg({"Customer_Satisfaction_Score":"mean"}).reset_index()
Avg_Customer_Satisfaction_Score_by_App_Usage_Frequency=Avg_Customer_Satisfaction_Score_by_App_Usage_Frequency.sort_values(by=["Customer_Satisfaction_Score"],ascending=[False])
Avg_Customer_Satisfaction_Score_by_App_Usage_Frequency["Customer_Satisfaction_Score"]=Avg_Customer_Satisfaction_Score_by_App_Usage_Frequency["Customer_Satisfaction_Score"].astype('int')
Avg_Customer_Satisfaction_Score_by_App_Usage_Frequency

  App_Usage_Frequency  Customer_Satisfaction_Score
1             Monthly                            5
2              Weekly                            5
0               Daily                            5

In [73]:
#Avg LTV by App_Usage_Frequency
Avg_LTV_by_App_Usage_Frequency=digital_wallet_df.groupby(["App_Usage_Frequency"]).agg({"LTV":"mean"}).reset_index()
Avg_LTV_by_App_Usage_Frequency=Avg_LTV_by_App_Usage_Frequency.sort_values(by=["LTV"],ascending=[False])
Avg_LTV_by_App_Usage_Frequency

  App_Usage_Frequency            LTV
2              Weekly  514093.548477
1             Monthly  512931.617338
0               Daily  508760.776166

#Preferred_Payment_Method

In [74]:
digital_wallet_df.columns

Index(['Customer_ID', 'Age', 'Location', 'Income_Level', 'Total_Transactions',
       'Avg_Transaction_Value', 'Max_Transaction_Value',
       'Min_Transaction_Value', 'Total_Spent', 'Active_Days',
       'Last_Transaction_Days_Ago', 'Loyalty_Points_Earned', 'Referral_Count',
       'Cashback_Received', 'App_Usage_Frequency', 'Preferred_Payment_Method',
       'Support_Tickets_Raised', 'Issue_Resolution_Time',
       'Customer_Satisfaction_Score', 'LTV'],
      dtype='object')

In [75]:
#Avg_transaction by Preferred_Payment_Method
Avg_transaction_by_payment_method=digital_wallet_df.groupby(by=["Preferred_Payment_Method"]).agg({"Total_Transactions":"mean"}).reset_index()
Avg_transaction_by_payment_method=Avg_transaction_by_payment_method.sort_values(by=["Total_Transactions"],ascending=[False])
Avg_transaction_by_payment_method["Total_Transactions"]=Avg_transaction_by_payment_method["Total_Transactions"].astype('int')
Avg_transaction_by_payment_method

  Preferred_Payment_Method  Total_Transactions
0              Credit Card                 515
2                      UPI                 501
1               Debit Card                 497
3           Wallet Balance                 491

In [76]:
#Avg_Transaction_Value by Preferred_Payment_Method
Avg_transaction_value_by_payment_method=digital_wallet_df.groupby(by=["Preferred_Payment_Method"]).agg({"Avg_Transaction_Value":"mean"}).reset_index()
Avg_transaction_value_by_payment_method=Avg_transaction_value_by_payment_method.sort_values(by=["Avg_Transaction_Value"],ascending=[False])
Avg_transaction_value_by_payment_method

  Preferred_Payment_Method  Avg_Transaction_Value
3           Wallet Balance           10004.521404
1               Debit Card            9986.556114
0              Credit Card            9947.584000
2                      UPI            9851.134612

In [77]:
#Avg_Max_Transaction_Value by Preferred_Payment_Method
Avg_Max_Transaction_Value_by_payment_method=digital_wallet_df.groupby(by=["Preferred_Payment_Method"]).agg({"Max_Transaction_Value":"mean"}).reset_index()
Avg_Max_Transaction_Value_by_payment_method=Avg_Max_Transaction_Value_by_payment_method.sort_values(by=["Max_Transaction_Value"],ascending=[False])
Avg_Max_Transaction_Value_by_payment_method

  Preferred_Payment_Method  Max_Transaction_Value
0              Credit Card           30447.919526
1               Debit Card           30223.925547
3           Wallet Balance           30091.722948
2                      UPI           29886.530059

In [78]:
#Avg_Min_Transaction_Value by Preferred_Payment_Method
Avg_Min_Transaction_Value_by_payment_method=digital_wallet_df.groupby(by=["Preferred_Payment_Method"]).agg({"Min_Transaction_Value":"mean"}).reset_index()
Avg_Min_Transaction_Value_by_payment_method=Avg_Min_Transaction_Value_by_payment_method.sort_values(by=["Min_Transaction_Value"],ascending=[False])
Avg_Min_Transaction_Value_by_payment_method

  Preferred_Payment_Method  Min_Transaction_Value
3           Wallet Balance            3024.933704
0              Credit Card            3002.398493
1               Debit Card            2969.381141
2                      UPI            2931.534534

In [79]:
#Avg_Total_Spent by Preferred_Payment_Method
Avg_Total_Spent_by_payment_method=digital_wallet_df.groupby(by=["Preferred_Payment_Method"]).agg({"Total_Spent":"mean"}).reset_index()
Avg_Total_Spent_by_payment_method=Avg_Total_Spent_by_payment_method.sort_values(by=["Total_Spent"],ascending=[False])
Avg_Total_Spent_by_payment_method["Total_Spent"]=Avg_Total_Spent_by_payment_method["Total_Spent"].astype('int')
Avg_Total_Spent_by_payment_method

  Preferred_Payment_Method  Total_Spent
0              Credit Card      5101039
3           Wallet Balance      4980695
2                      UPI      4968276
1               Debit Card      4961102

In [80]:
#Avg_Active_Days by Preferred_Payment_Method
Avg_Active_Days_by_payment_method=digital_wallet_df.groupby(by=["Preferred_Payment_Method"]).agg({"Active_Days":"mean"}).reset_index()
Avg_Active_Days_by_payment_method=Avg_Active_Days_by_payment_method.sort_values(by=["Active_Days"],ascending=[False])
Avg_Active_Days_by_payment_method["Active_Days"]=Avg_Active_Days_by_payment_method["Active_Days"].astype('int')
Avg_Active_Days_by_payment_method

  Preferred_Payment_Method  Active_Days
3           Wallet Balance          184
1               Debit Card          183
0              Credit Card          180
2                      UPI          179

In [81]:
#Avg_Loyalty_Points_Earned by Preferred_Payment_Method
Avg_Loyalty_Points_Earned_by_payment_method=digital_wallet_df.groupby(by=["Preferred_Payment_Method"]).agg({"Loyalty_Points_Earned":"mean"}).reset_index()
Avg_Loyalty_Points_Earned_by_payment_method=Avg_Loyalty_Points_Earned_by_payment_method.sort_values(by=["Loyalty_Points_Earned"],ascending=[False])
Avg_Loyalty_Points_Earned_by_payment_method["Loyalty_Points_Earned"]=Avg_Loyalty_Points_Earned_by_payment_method["Loyalty_Points_Earned"].astype('int')
Avg_Loyalty_Points_Earned_by_payment_method

  Preferred_Payment_Method  Loyalty_Points_Earned
0              Credit Card                   2544
3           Wallet Balance                   2494
2                      UPI                   2487
1               Debit Card                   2481

In [82]:
#Avg_Referral_Count by Preferred_Payment_Method
Avg_Referral_Count_by_payment_method=digital_wallet_df.groupby(by=["Preferred_Payment_Method"]).agg({"Referral_Count":"mean"}).reset_index()
Avg_Referral_Count_by_payment_method=Avg_Referral_Count_by_payment_method.sort_values(by=["Referral_Count"],ascending=[False])
Avg_Referral_Count_by_payment_method["Referral_Count"]=Avg_Referral_Count_by_payment_method["Referral_Count"].astype('int')
Avg_Referral_Count_by_payment_method

  Preferred_Payment_Method  Referral_Count
1               Debit Card              25
0              Credit Card              24
3           Wallet Balance              24
2                      UPI              24

In [83]:
#Avg_Referral_Count by Preferred_Payment_Method
Avg_Cashback_Received_by_payment_method=digital_wallet_df.groupby(by=["Preferred_Payment_Method"]).agg({"Cashback_Received":"mean"}).reset_index()
Avg_Cashback_Received_by_payment_method=Avg_Cashback_Received_by_payment_method.sort_values(by=["Cashback_Received"],ascending=[False])
Avg_Cashback_Received_by_payment_method

  Preferred_Payment_Method  Cashback_Received
0              Credit Card        2548.441318
2                      UPI        2526.347379
3           Wallet Balance        2477.557465
1               Debit Card        2434.421224

In [84]:
#Avg_Support_Tickets_Raised by Preferred_Payment_Method
Avg_Support_Tickets_Raised_by_payment_method=digital_wallet_df.groupby(by=["Preferred_Payment_Method"]).agg({"Support_Tickets_Raised":"mean"}).reset_index()
Avg_Support_Tickets_Raised_by_payment_method=Avg_Support_Tickets_Raised_by_payment_method.sort_values(by=["Support_Tickets_Raised"],ascending=[False])
Avg_Support_Tickets_Raised_by_payment_method["Support_Tickets_Raised"]=Avg_Support_Tickets_Raised_by_payment_method["Support_Tickets_Raised"].astype('int')
Avg_Support_Tickets_Raised_by_payment_method

  Preferred_Payment_Method  Support_Tickets_Raised
3           Wallet Balance                      10
2                      UPI                       9
1               Debit Card                       9
0              Credit Card                       9

In [85]:
#Avg_Issue_Resolution_Time by Preferred_Payment_Method
Avg_Issue_Resolution_Time_by_payment_method=digital_wallet_df.groupby(by=["Preferred_Payment_Method"]).agg({"Issue_Resolution_Time":"mean"}).reset_index()
Avg_Issue_Resolution_Time_by_payment_method=Avg_Issue_Resolution_Time_by_payment_method.sort_values(by=["Issue_Resolution_Time"],ascending=[False])
Avg_Issue_Resolution_Time_by_payment_method

  Preferred_Payment_Method  Issue_Resolution_Time
1               Debit Card              36.823984
0              Credit Card              36.735218
3           Wallet Balance              36.345336
2                      UPI              36.215977

In [86]:
#Avg_Customer_Satisfaction_Score by Preferred_Payment_Method
Avg_Customer_Satisfaction_Score_by_payment_method=digital_wallet_df.groupby(by=["Preferred_Payment_Method"]).agg({"Customer_Satisfaction_Score":"mean"}).reset_index()
Avg_Customer_Satisfaction_Score_by_payment_method=Avg_Customer_Satisfaction_Score_by_payment_method.sort_values(by=["Customer_Satisfaction_Score"],ascending=[False])
Avg_Customer_Satisfaction_Score_by_payment_method["Customer_Satisfaction_Score"]=Avg_Customer_Satisfaction_Score_by_payment_method["Customer_Satisfaction_Score"].astype('int')
Avg_Customer_Satisfaction_Score_by_payment_method

  Preferred_Payment_Method  Customer_Satisfaction_Score
1               Debit Card                            5
2                      UPI                            5
3           Wallet Balance                            5
0              Credit Card                            5

In [87]:
#Avg_LTV by Preferred_Payment_Method
Avg_LTV_by_payment_method=digital_wallet_df.groupby(by=["Preferred_Payment_Method"]).agg({"LTV":"mean"}).reset_index()
Avg_LTV_by_payment_method=Avg_LTV_by_payment_method.sort_values(by=["LTV"],ascending=[False])
Avg_LTV_by_payment_method

  Preferred_Payment_Method            LTV
0              Credit Card  521823.687288
3           Wallet Balance  509799.477331
2                      UPI  508490.165169
1               Debit Card  507869.441665

In [89]:
digital_cat_dummies=pd.get_dummies(digital_cat[['Location', 'Income_Level', 'App_Usage_Frequency','Preferred_Payment_Method']],drop_first=True)
digital_cat_dummies=digital_cat_dummies.astype('int')

In [126]:
digi_wallet=pd.concat([digital_cont,digital_cat_dummies],axis=1)

In [127]:
digi_wallet.corr()['LTV']

Age                                        0.007645
Total_Transactions                         0.650863
Avg_Transaction_Value                      0.664929
Max_Transaction_Value                      0.540410
Min_Transaction_Value                      0.537299
Total_Spent                                0.999949
Active_Days                               -0.016738
Last_Transaction_Days_Ago                 -0.003382
Loyalty_Points_Earned                      0.003852
Referral_Count                            -0.023315
Cashback_Received                         -0.011485
Support_Tickets_Raised                    -0.029762
Issue_Resolution_Time                     -0.001180
Customer_Satisfaction_Score                0.014858
LTV                                        1.000000
Location_Suburban                          0.013570
Location_Urban                            -0.006972
Income_Level_Low                          -0.002984
Income_Level_Middle                        0.018034
App_Usage_Frequency_Monthly                0.001628
App_Usage_Frequency_Weekly                 0.003492
Preferred_Payment_Method_Debit Card       -0.005349
Preferred_Payment_Method_UPI              -0.004581
Preferred_Payment_Method_Wallet Balance   -0.002773
Name: LTV, dtype: float64

In [91]:
digi_wallet['Loyalty_Points_Earned'].corr(digi_wallet['Total_Spent'])

np.float64(-0.002867303442433305)